### ISSUE TITLE
NPE trying to us the node/repl-env in new clojurescript

### ISSUE THREAD

**Issue by rhg** [cemerick/piggieback#35]
The newer builds of cljs have a node repl which works fine without piggieback/nrepl as per http://swannodette.github.io/2014/12/31/the-old-way-the-new-way/ except im using the latest release not from git (0.0-2655). I'm also using clojure 1.7.0-alpha4 and piggieback 0.1.3.

**Comment by cemerick** [comment]
Yes, piggieback likely requires updating to work with the latest changes to how ClojureScript REPLs work. I have not yet looked at what's necessary in detail. Happy to take a PR if someone would like to contribute.

**Comment by rhg** [comment]
I'll dig in later today and send a PR.

**Comment by nbeloglazov** [comment]
Have similar problem with latest clojurescript `0.0-2665` and cljx which uses piggieback. Can't start regular clojure repl. Example project.clj:
```clojure
(defproject bug "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [org.clojure/clojurescript "0.0-2665"]]
  :plugins [[com.keminglabs/cljx "0.5.0"]])
```
And the error of running `lein repl`:
```text
Error loading cljx.repl-middleware: java.lang.IllegalArgumentException: No single method: _setup of interface: cljs.repl.IJavaScriptEnv found for function: -setup of protocol: IJavaScriptEnv, compiling:(cemerick/piggieback.clj:149:5)
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: cljx.repl-middleware/wrap-cljx in this context, compiling:(/tmp/form-init6807809113808791412.clj:1:5337)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6651)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
```

**Comment by viesti** [comment]
David Nolen has been quite active :) The above exception stems from API changes: https://github.com/clojure/clojurescript/wiki/Custom-REPLs#expectations

**Comment by nbeloglazov** [comment]
Cljx issue it not actually related to this one because cljx started to happen only in clojurescript 0265 version while this one started in 2655. I've created a separate issue: #36. Sorry for confusion.
