### ISSUE TITLE
Broken compatibility with clojurescript 0.0-2655

### ISSUE THREAD

**Issue by nbeloglazov** [cemerick/piggieback#36]
Cannot start regular repl in a project that uses clojurescript `0.0-2665` and cljx which uses piggieback. Example project.clj:
```clojure
(defproject bug "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [org.clojure/clojurescript "0.0-2665"]]
  :plugins [[com.keminglabs/cljx "0.5.0"]])
```
And the error when running `lein repl`:
```text
Error loading cljx.repl-middleware: java.lang.IllegalArgumentException: No single method: _setup of interface: cljs.repl.IJavaScriptEnv found for function: -setup of protocol: IJavaScriptEnv, compiling:(cemerick/piggieback.clj:149:5)
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: cljx.repl-middleware/wrap-cljx in this context, compiling:(/tmp/form-init6807809113808791412.clj:1:5337)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6651)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
```

**Comment by nbeloglazov** [comment]
[@vlesti](https://github.com/viesti) noted that it is caused by recent changes in clojurescript API: https://github.com/clojure/clojurescript/wiki/Custom-REPLs#expectations
